<?php
 $aik =  array (
  'sitename' => '残月解析',
  'pcdomain' => 'http://127.0.0.1:8080',
  'title' => '残月解析',
  'keywords' => 'VIP在线解析',
  'description' => '本站为广大网友提供: 腾讯视频VIP解析，爱奇艺VIP解析，优酷VIP解析，欢迎大家收藏本站 ',
  'gonggao' => '<p>若视频播放异常，请尝试【更换线路】或【刷新】即可解决 </p><p>如有线路不行，请把网页拉倒最下方，发邮件给站长，电脑端上体验最佳，手机端容易出现线路商的广告服务</p>',
  'maurl' => 'https://www.iqiyi.com/v_2e53qe1sdv0.html',
  'jiekou1name' => '解析线路1',
  'jiekou1' => 'https://api.qianqi.net/vip/?url=',
  'jiekou2name' => '解析线路2',
  'jiekou2' => 'https://jx.nnxv.cn/tv.php?url=',
  'jiekou3name' => '解析线路3',
  'jiekou3' => 'https://jx.aidouer.net/?url=',
  'jiekou4name' => '解析线路4',
  'jiekou4' => 'https://',
  'jiekou5name' => '解析线路5',
  'jiekou5' => 'http://',
  'jiekou6name' => '解析线路6',
  'jiekou6' => 'http://',
  'jiekou7name' => '解析线路7',
  'jiekou7' => 'http://',
  'jiekou8name' => '解析线路8',
  'jiekou8' => 'http://',
  'jiekou9name' => '解析线路9',
  'jiekou9' => 'http://',
  'jiekou10name' => '解析线路10',
  'jiekou10' => 'http://',
  'topnav' => '',
  'foot' => '本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传 ',
  'tongji' => '',
  'admin_email' => '1771245847@qq.com',
);
?>
